import { and, eq } from "drizzle-orm";
import type { db } from "~/server/db";
import {
  categories,
  materials,
  partDefinitions,
  partSynonyms,
  partTypes,
  sizes,
  suppliers,
  supplierParts,
  units,
} from "~/server/db/schema";
// Import material catalogue from JSON (generated by scripts/parse_excel_to_json.py)
import materialCatalogueData from "./material-catalogue.json";

type Database = typeof db;

// Type definition for parsed parts from JSON
interface ParsedPart {
  displayName: string;
  description: string;
  material: string;
  sizeNominal: number;
  sizeUnit: string;
  categoryName: string;
  partType: string;
  synonyms: string[];
}

// Seed data constants
const unitDefinitions = [
  { code: "in", kind: "length", displayName: "Inch" },
  { code: "ft", kind: "length", displayName: "Foot" },
  { code: "mm", kind: "length", displayName: "Millimeter" },
  { code: "ea", kind: "count", displayName: "Each" },
];

// Root categories only - matching the Excel categories
const rootCategories = ["Fittings", "Pipe", "Valves"];

// Parse and type-check the JSON data
const partDefinitionsData: ParsedPart[] = materialCatalogueData as ParsedPart[];

export interface SeedProgress {
  totalParts: number;
  completedParts: number;
  currentOperation: string;
  percentage: number;
}

type ProgressCallback = (progress: SeedProgress) => void | Promise<void>;

/**
 * Seed an organization with default parts, categories, materials, and part types
 * Uses data from Material Catalogue Excel file
 */
export async function seedOrganization(
  db: Database,
  organizationId: string,
  onProgress?: ProgressCallback,
): Promise<void> {
  const updateProgress = async (
    current: number,
    total: number,
    operation: string,
  ) => {
    const progress: SeedProgress = {
      totalParts: total,
      completedParts: current,
      currentOperation: operation,
      percentage: Math.round((current / total) * 100),
    };

    console.log(`[${progress.percentage}%] ${operation} (${current}/${total})`);

    if (onProgress) {
      await onProgress(progress);
    }
  };

  console.log("\n🌱 Starting organization seed...");

  // Step 1: Load Material Catalogue from JSON
  console.log("\n📖 Loading Material Catalogue from JSON...");
  // partDefinitionsData is imported from JSON at the top of the file
  const totalParts = partDefinitionsData.length;

  console.log(`✅ Loaded ${totalParts} parts from catalogue`);
  await updateProgress(0, totalParts, "Initializing");

  // Step 2: Create or get units (global, so check if they exist first)
  console.log("\n📏 Setting up units...");
  const unitMap = new Map<string, string>();
  for (const unitDef of unitDefinitions) {
    const [existing] = await db
      .select()
      .from(units)
      .where(eq(units.code, unitDef.code))
      .limit(1);

    if (existing) {
      unitMap.set(unitDef.code, existing.id);
    } else {
      const [unit] = await db
        .insert(units)
        .values(unitDef)
        .returning({ id: units.id });
      if (unit) {
        unitMap.set(unitDef.code, unit.id);
      }
    }
  }
  console.log(`✅ ${unitMap.size} units ready`);

  // Step 3: Create root categories only (no child categories)
  console.log("\n📁 Creating categories...");
  const categoryMap = new Map<string, string>();

  for (const categoryName of rootCategories) {
    const [existing] = await db
      .select()
      .from(categories)
      .where(
        and(
          eq(categories.name, categoryName),
          eq(categories.organizationId, organizationId),
        ),
      )
      .limit(1);

    if (existing) {
      categoryMap.set(categoryName, existing.id);
    } else {
      const [category] = await db
        .insert(categories)
        .values({
          organizationId: organizationId,
          name: categoryName,
          sortOrder: 0,
        })
        .returning({ id: categories.id });
      if (!category) {
        throw new Error(`Failed to create category ${categoryName}`);
      }
      categoryMap.set(categoryName, category.id);
    }
  }
  console.log(`✅ ${categoryMap.size} categories ready`);

  // Step 4: Create materials (org-specific) - from Excel data
  console.log("\n🎨 Creating materials...");
  const materialSet = new Set<string>();
  for (const partData of partDefinitionsData) {
    if (partData.material) {
      materialSet.add(partData.material);
    }
  }

  const materialMap = new Map<string, string>();
  for (const materialName of Array.from(materialSet)) {
    const [existing] = await db
      .select()
      .from(materials)
      .where(
        and(
          eq(materials.name, materialName),
          eq(materials.organizationId, organizationId),
        ),
      )
      .limit(1);

    if (existing) {
      materialMap.set(materialName, existing.id);
    } else {
      const [material] = await db
        .insert(materials)
        .values({
          organizationId: organizationId,
          name: materialName,
        })
        .returning({ id: materials.id });
      if (material) {
        materialMap.set(materialName, material.id);
      }
    }
  }
  console.log(
    `✅ ${materialMap.size} materials created: ${Array.from(materialSet).join(", ")}`,
  );

  // Step 5: Create part types (org-specific)
  console.log("\n🔧 Creating part types...");
  const partTypeSet = new Set<string>();
  for (const partData of partDefinitionsData) {
    if (partData.partType) {
      partTypeSet.add(partData.partType);
    }
  }

  const partTypeMap = new Map<string, string>();
  for (const partTypeName of Array.from(partTypeSet)) {
    const [existing] = await db
      .select()
      .from(partTypes)
      .where(
        and(
          eq(partTypes.name, partTypeName),
          eq(partTypes.organizationId, organizationId),
        ),
      )
      .limit(1);

    if (existing) {
      partTypeMap.set(partTypeName, existing.id);
    } else {
      const [partType] = await db
        .insert(partTypes)
        .values({
          organizationId: organizationId,
          name: partTypeName,
        })
        .returning({ id: partTypes.id });
      if (partType) {
        partTypeMap.set(partTypeName, partType.id);
      }
    }
  }
  console.log(
    `✅ ${partTypeMap.size} part types created: ${Array.from(partTypeSet).join(", ")}`,
  );

  // Step 6: Create sizes (org-specific)
  console.log("\n📐 Creating sizes...");
  const sizeSet = new Set<string>();
  for (const partData of partDefinitionsData) {
    if (
      partData.sizeNominal !== null &&
      partData.sizeNominal !== undefined &&
      partData.sizeUnit
    ) {
      const sizeKey = `${partData.sizeNominal}_${partData.sizeUnit}`;
      sizeSet.add(sizeKey);
    }
  }

  const sizeMap = new Map<string, string>();
  for (const sizeKey of Array.from(sizeSet)) {
    const parts = sizeKey.split("_");
    if (parts.length !== 2) continue;

    const [nominalStr, unitCode] = parts;
    if (!nominalStr || !unitCode) continue;

    const nominal = parseFloat(nominalStr);
    if (isNaN(nominal)) continue;

    const unitId = unitMap.get(unitCode);
    if (!unitId) continue;

    const [existing] = await db
      .select()
      .from(sizes)
      .where(
        and(
          eq(sizes.organizationId, organizationId),
          eq(sizes.nominal, nominal.toString()),
          eq(sizes.unitId, unitId),
        ),
      )
      .limit(1);

    if (existing) {
      sizeMap.set(sizeKey, existing.id);
    } else {
      const [size] = await db
        .insert(sizes)
        .values({
          organizationId: organizationId,
          nominal: nominal.toString(),
          unitId: unitId,
        })
        .returning({ id: sizes.id });
      if (size) {
        sizeMap.set(sizeKey, size.id);
      }
    }
  }
  console.log(`✅ ${sizeMap.size} sizes created`);

  // Step 7: Create parts with progress tracking
  console.log("\n🔩 Creating parts...");
  const defaultUomId = unitMap.get("ea");
  if (!defaultUomId) {
    throw new Error('Unit "ea" not found - required for default UOM');
  }

  let createdCount = 0;
  let skippedCount = 0;

  for (let i = 0; i < partDefinitionsData.length; i++) {
    const partData = partDefinitionsData[i];
    if (!partData) {
      continue;
    }

    // Update progress every 10 parts
    if (i % 10 === 0 || i === partDefinitionsData.length - 1) {
      await updateProgress(
        i + 1,
        totalParts,
        `Creating parts (${createdCount} new, ${skippedCount} existing)`,
      );
    }

    const categoryId = categoryMap.get(partData.categoryName);
    if (!categoryId) {
      console.warn(
        `⚠️  Category "${partData.categoryName}" not found for part "${partData.displayName}"`,
      );
      continue;
    }

    const sizeKey =
      partData.sizeNominal !== null &&
      partData.sizeNominal !== undefined &&
      partData.sizeUnit
        ? `${partData.sizeNominal}_${partData.sizeUnit}`
        : null;
    let sizeId = sizeKey ? (sizeMap.get(sizeKey) ?? null) : null;

    // If no sizeId found but we have size data, create it
    if (!sizeId && sizeKey) {
      const parts = sizeKey.split("_");
      if (parts.length === 2) {
        const [nominalStr, unitCode] = parts;
        const nominal = parseFloat(nominalStr ?? "0");
        const unitId = unitMap.get(unitCode ?? "");
        if (unitId && !isNaN(nominal)) {
          const [newSize] = await db
            .insert(sizes)
            .values({
              organizationId: organizationId,
              nominal: nominal.toString(),
              unitId: unitId,
            })
            .returning({ id: sizes.id });
          if (newSize) {
            sizeId = newSize.id;
            sizeMap.set(sizeKey, newSize.id);
          }
        }
      }
    }

    // If still no sizeId, create a default "no size" size
    if (!sizeId) {
      const defaultSizeKey = "0_ea";
      let defaultSizeId = sizeMap.get(defaultSizeKey);
      if (!defaultSizeId) {
        const defaultUnitId = unitMap.get("ea");
        if (defaultUnitId) {
          const [newDefaultSize] = await db
            .insert(sizes)
            .values({
              organizationId: organizationId,
              nominal: "0",
              unitId: defaultUnitId,
            })
            .returning({ id: sizes.id });
          if (newDefaultSize) {
            defaultSizeId = newDefaultSize.id;
            sizeMap.set(defaultSizeKey, newDefaultSize.id);
          }
        }
      }
      sizeId = defaultSizeId ?? null;
    }

    if (!sizeId) {
      console.warn(
        `⚠️  Failed to get or create size for part "${partData.displayName}"`,
      );
      continue;
    }

    const materialId = partData.material
      ? (materialMap.get(partData.material) ?? null)
      : null;

    const partTypeId = partData.partType
      ? (partTypeMap.get(partData.partType) ?? null)
      : null;

    // Check if part already exists
    const [existing] = await db
      .select()
      .from(partDefinitions)
      .where(
        and(
          eq(partDefinitions.displayName, partData.displayName),
          eq(partDefinitions.organizationId, organizationId),
        ),
      )
      .limit(1);

    if (existing) {
      skippedCount++;
      continue;
    }

    const [part] = await db
      .insert(partDefinitions)
      .values({
        organizationId: organizationId,
        categoryId: categoryId,
        displayName: partData.displayName,
        description: partData.description,
        imageUrl: null,
        partTypeId: partTypeId,
        materialId: materialId,
        sizeId: sizeId ?? null,
        defaultUomId: defaultUomId,
        isActive: true,
      })
      .returning({ id: partDefinitions.id });

    if (part) {
      createdCount++;

      // Create synonyms
      for (const synonym of partData.synonyms) {
        await db.insert(partSynonyms).values({
          partDefinitionId: part.id,
          synonym: synonym,
        });
      }
    }
  }

  await updateProgress(
    totalParts,
    totalParts,
    `Parts complete (${createdCount} new, ${skippedCount} existing)`,
  );

  // Step 8: Create a default supplier for the organization
  console.log("\n🏪 Creating default supplier...");
  const [defaultSupplier] = await db
    .select()
    .from(suppliers)
    .where(
      and(
        eq(suppliers.name, "Default Supplier"),
        eq(suppliers.organizationId, organizationId),
      ),
    )
    .limit(1);

  let supplierId: string;
  if (defaultSupplier) {
    supplierId = defaultSupplier.id;
    console.log("✅ Using existing default supplier");
  } else {
    const [newSupplier] = await db
      .insert(suppliers)
      .values({
        organizationId: organizationId,
        name: "Default Supplier",
        contactEmail: null,
        contactPhone: null,
        orderingNotes: null,
        locationId: null,
      })
      .returning({ id: suppliers.id });
    if (!newSupplier) {
      throw new Error("Failed to create default supplier");
    }
    supplierId = newSupplier.id;
    console.log("✅ Created default supplier");
  }

  // Step 9: Create supplier parts with ZERO prices
  console.log("\n💰 Creating supplier parts (all prices set to 0.00)...");
  const allParts = await db
    .select({
      id: partDefinitions.id,
      displayName: partDefinitions.displayName,
    })
    .from(partDefinitions)
    .where(eq(partDefinitions.organizationId, organizationId));

  const packUomId = unitMap.get("ea");
  if (!packUomId) {
    throw new Error('Unit "ea" not found - required for supplier parts');
  }

  let supplierPartCount = 0;
  const totalSupplierParts = allParts.length;

  for (let i = 0; i < allParts.length; i++) {
    const part = allParts[i];
    if (!part) {
      continue;
    }

    // Update progress every 50 supplier parts
    if (i % 50 === 0 || i === allParts.length - 1) {
      await updateProgress(
        i + 1,
        totalSupplierParts,
        `Creating supplier parts (${supplierPartCount} new)`,
      );
    }

    // Check if supplier part already exists
    const [existing] = await db
      .select()
      .from(supplierParts)
      .where(
        and(
          eq(supplierParts.partDefinitionId, part.id),
          eq(supplierParts.organizationId, organizationId),
          eq(supplierParts.supplierId, supplierId),
        ),
      )
      .limit(1);

    if (existing) {
      continue;
    }

    const sku = part.displayName
      .replace(/[^a-zA-Z0-9]/g, "")
      .substring(0, 20)
      .toUpperCase();

    await db.insert(supplierParts).values({
      organizationId: organizationId,
      supplierId: supplierId,
      partDefinitionId: part.id,
      supplierSku: `${sku}-${Math.floor(Math.random() * 1000)}`,
      supplierName: part.displayName,
      packSize: "1",
      packUomId: packUomId,
      lastKnownUnitCost: "0.00", // ALL PRICES SET TO ZERO
      currency: "CAD",
      isPreferred: true,
      notes: null,
    });

    supplierPartCount++;
  }

  await updateProgress(
    totalSupplierParts,
    totalSupplierParts,
    `Supplier parts complete (${supplierPartCount} new)`,
  );

  console.log("\n🎉 Organization seed completed successfully!");
  console.log(`📊 Summary:`);
  console.log(`   - Parts: ${createdCount} new, ${skippedCount} existing`);
  console.log(`   - Materials: ${materialMap.size}`);
  console.log(`   - Part Types: ${partTypeMap.size}`);
  console.log(`   - Categories: ${categoryMap.size}`);
  console.log(`   - Supplier Parts: ${supplierPartCount}`);
  console.log(`   - All prices: $0.00 CAD`);
}
